# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevapregunta',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
