# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0003_auto_20151230_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nuevapregunta',
            old_name='revisado',
            new_name='cerrado',
        ),
        migrations.AddField(
            model_name='nuevapregunta',
            name='contacto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
