# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0004_auto_20151230_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevapregunta',
            name='contacto',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
