# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0007_auto_20160108_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevapregunta',
            name='fecha_llamada',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
