# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0008_nuevapregunta_fecha_llamada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevapregunta',
            name='fecha_llamada',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
