# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0012_datoextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoextra',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
